# Generated by Django 3.1.5 on 2021-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(default='Test Description', max_length=200),
        ),
    ]
