# Generated by Django 3.1.5 on 2021-11-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_poll_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='category',
            new_name='date_now',
        ),
    ]
