# Generated by Django 3.1.5 on 2021-11-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_auto_20211122_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.CharField(default='general', max_length=15),
        ),
    ]
